send error to STDERR

diff --git a/tts b/tts
--- a/tts
+++ b/tts
@@ -163,7 +163,7 @@ LIST)
 			;;
 		esac
 	else
-		printf 'API Error: %s\n' "$API_ERROR"
+		printf 'API Error: %s\n' "$API_ERROR" >&2
 	fi
 	;;
 esac
